site_name: Multi Tenant Operator
docs_dir: content
site_url: https://docs.stakater.com/mto/
repo_url: https://github.com/stakater/mto-docs
edit_uri: blob/main/content/

nav:
    - index.md
    - Installation:
      - tutorials/installation.md
    - Tutorials:
      - Interacting with Templates:
        - tutorials/tenant/create-tenant.md
        - tutorials/tenant/create-sandbox.md
        - tutorials/tenant/creating-namespaces.md
        - tutorials/tenant/assigning-metadata.md
        - tutorials/tenant/tenant-hibernation.md
        - tutorials/tenant/deleting-tenant.md
        - tutorials/template/template.md
      - Expand tutorials section:
        - expand-section
      # - ArgoCD Multi-tenancy:
      # - Vault Multi-Tenancy:
    - How-to Guides:
      - reference-guides/admin-clusterrole.md
      - reference-guides/configuring-multitenant-network-isolation.md
      - reference-guides/custom-roles.md
      - reference-guides/deploying-templates.md
      - reference-guides/distributing-resources.md
      - reference-guides/distributing-secrets.md
      - reference-guides/resource-sync-by-tgi.md
      - reference-guides/distributing-secrets-using-sealed-secret-template.md
      - reference-guides/deploying-private-helm-charts.md
      - reference-guides/extend-default-roles.md
      - tutorials/argocd/enabling-multi-tenancy-argocd.md
      - reference-guides/integrationconfig.md
      - reference-guides/mattermost.md
      - reference-guides/secret-distribution.md
      - reference-guides/custom-metrics.md
      - reference-guides/graph-visualization.md      
      - Offboarding:
        - how-to-guides/offboarding/uninstalling.md
    # - Reference guides:
    #   - explanation/console.md

    - Explanation:
      - explanation/console.md
      - explanation/auth.md
      - explanation/why-argocd-multi-tenancy.md
      - tutorials/vault/enabling-multi-tenancy-vault.md
    - CRDs API Reference:
      - crds-api-reference/integration-config.md
      - crds-api-reference/tenant.md
      - crds-api-reference/quota.md
      - crds-api-reference/template-group-instance.md
      - crds-api-reference/template-instance.md
      - crds-api-reference/template.md
    # - faq.md
    - changelog.md
    - eula.md
    - troubleshooting.md
