site_name: Multi Tenant Operator
docs_dir: content
site_url: https://docs.stakater.com/mto/
repo_url: https://github.com/stakater/mto-docs
edit_uri: blob/main/content/
theme:
  favicon: assets/images/favicon.svg

strict: true
validation:
  links:
    anchors: warn

extra:
  version:
    provider: mike
    default: latest

nav:
  - index.md
  - About:
      - about/key-features.md
      - about/use-cases.md
      - about/benefits.md
  - Architecture:
      - architecture/architecture.md
      - architecture/concepts.md
  - Installation:
      - installation/overview.md
      - installation/openshift.md
      - installation/azure-aks.md
      - On EKS:
          - Preparation: 'installation/aws-eks/preparation.md'
          - Installation: 'installation/aws-eks/installation.md'
          - Validation: 'installation/aws-eks/validation.md'
      - installation/kubernetes.md
      - installation/helm.md
  - Navigating Console:
      - console/overview.md
      - console/dashboard.md
      - console/tenants.md
      - console/namespaces.md
      - console/hibernation.md
      - console/showback.md
      - console/quotas.md
      - console/templates.md
      - console/capacity-planning.md
      - console/configuration.md
  - Kubernetes Resources:
      - kubernetes-resources/quota.md
      - Tenant:
          - kubernetes-resources/tenant/tenant-overview.md
          - kubernetes-resources/tenant/create-tenant.md
          - kubernetes-resources/tenant/create-namespaces.md         
          - kubernetes-resources/tenant/create-sandbox.md
          - kubernetes-resources/tenant/assign-metadata.md
          - kubernetes-resources/tenant/hibernate-tenant.md
          - kubernetes-resources/tenant/delete-tenant.md
      - kubernetes-resources/extensions.md
      - Template:
          - kubernetes-resources/template/template.md
          - kubernetes-resources/template/template-instance.md
          - kubernetes-resources/template/template-group-instance.md
          - Use Cases:
              - kubernetes-resources/template/use-cases/copying-resources.md
              - kubernetes-resources/template/use-cases/distributing-manifests.md
              - kubernetes-resources/template/use-cases/configuring-multitenant-network-isolation.md
              - kubernetes-resources/template/use-cases/deploying-templates.md
              - kubernetes-resources/template/use-cases/resource-sync-by-tgi.md                            
              - kubernetes-resources/template/use-cases/distributing-secrets-using-sealed-secret-template.md
              - kubernetes-resources/template/use-cases/deploying-private-helm-charts.md
      - kubernetes-resources/integration-config.md
      - kubernetes-resources/resource-supervisor.md
  - Integrations:
      - integrations/argocd.md
      - Vault:
          - integrations/vault/vault.md
          - integrations/vault/vault-ic.md
          - integrations/vault/vault-kc-entraid.md
      - integrations/devworkspace.md
      - integrations/mattermost.md
  - How-to Guides:
      - RBAC:
          - how-to-guides/custom-roles.md
          - how-to-guides/extend-default-roles.md
      - Integrations:
          - how-to-guides/integrating-external-keycloak.md
          - how-to-guides/azure-pricing.md
      - Tenant Isolation:
          - how-to-guides/restrict-nodepool-per-tenant.md
      - Offboarding:
          - how-to-guides/offboarding/uninstalling.md
      - how-to-guides/custom-metrics.md
  - Explanation:
      - Tenant Policies:
          - explanation/tenant-policies/networking.md
      - explanation/logs-metrics.md
      - explanation/template.md
      - explanation/templated-metadata-values.md
  - pricing.md
  - changelog.md
  - eula.md
  - troubleshooting.md
