site_name: Multi Tenant Operator
docs_dir: content
site_url: https://docs.stakater.com/mto/
repo_url: https://github.com/stakater/mto-docs
edit_uri: blob/main/content/
theme:
  favicon: assets/images/favicon.svg

strict: true
validation:
  links:
    anchors: warn

extra:
  version:
    provider: mike
    default: latest

nav:
  - index.md
  - About:
      - about/key-features.md
      - about/use-cases.md
      - about/benefits.md
  - Installation:
      - installation/overview.md
      - installation/openshift.md
      - installation/azure-aks.md
      - On EKS:
          - Prerequistes: 'installation/aws-eks/mto-prereq-installation.md'
          - Installation: 'installation/aws-eks/mto-installation.md'
          - Validation: 'installation/aws-eks/create-tenants.md'
      - installation/kubernetes.md
      - installation/helm.md
  - Architecture:
     - architecture/architecture.md
     - architecture/concepts.md     
  - pricing.md
  - Tutorials:
      - Configuring Tenants:
          - tutorials/tenant/create-tenant.md
          - tutorials/tenant/create-sandbox.md
          - tutorials/tenant/creating-namespaces.md
          - tutorials/tenant/assigning-metadata.md
          - tutorials/tenant/tenant-hibernation.md
          - tutorials/tenant/deleting-tenant.md
      - Interacting with Templates:
          - tutorials/distributing-resources/copying-resources.md
          - tutorials/distributing-resources/distributing-manifests.md
  - How-to Guides:
      - RBAC:
          - how-to-guides/custom-roles.md
          - how-to-guides/extend-default-roles.md
      - Resource Distribution:
          - how-to-guides/configuring-multitenant-network-isolation.md
          - how-to-guides/deploying-templates.md
          - how-to-guides/resource-sync-by-tgi.md
          - how-to-guides/distributing-secrets-using-sealed-secret-template.md
          - how-to-guides/deploying-private-helm-charts.md
          - how-to-guides/copying-resources.md
      - Console:
          - how-to-guides/keycloak.md
          - how-to-guides/custom-metrics.md
          - how-to-guides/graph-visualization.md
          - how-to-guides/hibernation-workflow.md
      - Integrations:
          - how-to-guides/enabling-multi-tenancy-argocd.md
          - how-to-guides/enabling-multi-tenancy-vault.md
          - how-to-guides/enabling-openshift-dev-workspace.md
          - how-to-guides/mattermost.md
          - how-to-guides/integrating-external-keycloak.md
          - how-to-guides/integrating-vault.md
          - how-to-guides/azure-pricing.md
      - Tenant Isolation:
          - how-to-guides/restrict-nodepool-per-tenant.md
      - Offboarding:
          - how-to-guides/offboarding/uninstalling.md
  - Explanation:
      - Tenant Policies:
        - explanation/tenant-policies/networking.md
      - explanation/logs-metrics.md
      - explanation/template.md
      - explanation/console.md
      - explanation/templated-metadata-values.md
      - explanation/multi-tenancy-vault.md
  - CRDs API Reference:
      - crds-api-reference/quota.md
      - crds-api-reference/tenant.md
      - crds-api-reference/extensions.md
      - crds-api-reference/template.md
      - crds-api-reference/template-instance.md
      - crds-api-reference/template-group-instance.md
      - crds-api-reference/integration-config.md
      - crds-api-reference/resource-supervisor.md
  - changelog.md
  - eula.md
  - troubleshooting.md
