site_name: Multi Tenant Operator
docs_dir: content
site_url: https://docs.stakater.com/mto/
repo_url: https://github.com/stakater/mto-docs
edit_uri: blob/main/content/
theme:
  favicon: assets/images/favicon.svg

strict: true
validation:
  links:
    anchors: warn

extra:
  version:
    provider: mike
    default: latest

nav:
  - index.md
  - About:
      - about/key-features.md
      - about/use-cases.md
      - about/benefits.md
  - Architecture:
      - architecture/architecture.md
      - architecture/custom-metrics.md
      - architecture/logs-metrics.md      
  - Installation:
      - installation/overview.md
      - installation/openshift.md
      - On AKS:
          - Prepration: 'installation/azure-aks/preparation.md'
          - Installation: 'installation/azure-aks/installation.md'
          - Validation: 'installation/azure-aks/validation.md'
      - On EKS:
          - Preparation: 'installation/aws-eks/preparation.md'
          - Installation: 'installation/aws-eks/installation.md'
          - Validation: 'installation/aws-eks/validation.md'
      - installation/kubernetes.md
      - installation/helm.md
  - Navigating Console:
      - console/overview.md
      - console/dashboard.md
      - console/tenants.md
      - console/namespaces.md
      - console/hibernation.md
      - console/showback.md
      - console/quotas.md
      - console/templates.md
      - console/capacity-planning.md
      - console/configuration.md
  - Kubernetes Resources:
      - architecture/concepts.md
      - kubernetes-resources/quota.md
      - Tenant:
          - kubernetes-resources/tenant/tenant-overview.md
          - How-to Guides:
              - kubernetes-resources/tenant/how-to-guides/create-tenant.md
              - kubernetes-resources/tenant/how-to-guides/create-namespaces.md         
              - kubernetes-resources/tenant/how-to-guides/create-sandbox.md
              - kubernetes-resources/tenant/how-to-guides/assign-metadata.md
              - kubernetes-resources/tenant/how-to-guides/hibernate-tenant.md
              - kubernetes-resources/tenant/how-to-guides/restrict-nodepool-per-tenant.md
              - kubernetes-resources/tenant/how-to-guides/disable-intra-tenant-networking.md
              - kubernetes-resources/tenant/how-to-guides/ingress-sharding.md
              - kubernetes-resources/tenant/how-to-guides/custom-roles.md
              - kubernetes-resources/tenant/how-to-guides/extend-default-roles.md
              - kubernetes-resources/tenant/how-to-guides/delete-tenant.md
      - kubernetes-resources/extensions.md
      - Template:
          - kubernetes-resources/template/template.md
          - kubernetes-resources/template/template-instance.md
          - kubernetes-resources/template/template-group-instance.md
          - How-to Guides:
              - kubernetes-resources/template/how-to-guides/copying-resources.md
              - kubernetes-resources/template/how-to-guides/copying-resources-2.md
              - kubernetes-resources/template/how-to-guides/distributing-manifests.md
              - kubernetes-resources/template/how-to-guides/configuring-multitenant-network-isolation.md
              - kubernetes-resources/template/how-to-guides/deploying-templates.md
              - kubernetes-resources/template/how-to-guides/resource-sync-by-tgi.md                            
              - kubernetes-resources/template/how-to-guides/distributing-secrets-using-sealed-secret-template.md
              - kubernetes-resources/template/how-to-guides/deploying-private-helm-charts.md
              - kubernetes-resources/template/how-to-guides/templated-metadata-values.md
              - kubernetes-resources/template/how-to-guides/template-default-params.md
      - kubernetes-resources/integration-config.md
      - kubernetes-resources/resource-supervisor.md
  - Integrations:
      - integrations/argocd.md
      - Vault:
          - integrations/vault/vault.md
          - integrations/vault/vault-ic.md
          - integrations/vault/vault-kc-entraid.md
      - integrations/devworkspace.md
      - integrations/mattermost.md
      - integrations/keycloak.md
      - integrations/azure-pricing.md
      - integrations/aws-pricing.md
  - pricing.md
  - changelog.md
  - eula.md
  - troubleshooting.md
