site_name: Multi Tenant Operator
docs_dir: content
site_url: https://docs.stakater.com/
repo_url: https://github.com/stakater/mto-docs
edit_uri: blob/main/content/
use_directory_urls: false
theme:
    name: material
    prev_next_buttons_location: none
    logo: assets/images/favicon.svg
    favicon: assets/images/favicon.svg
    custom_dir: custom_theme/
    palette:
        primary: white
    features:
        - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
    analytics:
        provider: google
        property: G-TTH1YYW5TX
    consent:
        title: Cookie consent
        actions:
            - accept
            - reject
            - manage
        description: >-
            We use cookies to recognize your repeated visits and preferences, as well
            as to measure the effectiveness of our documentation and whether users
            find what they're searching for. With your consent, you're helping us to
            make our documentation better.
    version:
        provider: mike
        default: latest

nav:
    - index.md
    - eula.md
    - features.md
    - installation.md
    - integration-config.md
    - customresources.md
    - tenant-roles.md
    - Use Cases:
        - usecases/quota.md
        - usecases/tenant.md
        - usecases/namespace.md
        - usecases/volume-limits.md
        - usecases/template.md
        - usecases/deploying-templates.md
        - usecases/distributing-resources.md
        - usecases/extend-default-roles.md
        - usecases/custom-roles.md
        - usecases/secret-distribution.md
        - usecases/configuring-multitenant-network-isolation.md
        - usecases/distributing-secrets-using-sealed-secret-template.md
        - usecases/integrationconfig.md
        - usecases/argocd.md
        - usecases/mattermost.md
        - usecases/admin-clusterrole.md
        - usecases/hibernation.md
        - usecases/private-sandboxes.md
    - hibernation.md
    - argocd-multitenancy.md
    - vault-multitenancy.md
    - changelog.md
    - troubleshooting.md
    - faq.md
plugins:
    - search
    - mermaid2
    - glightbox
