docs_dir: content
edit_uri: blob/main/content/
extra:
  analytics:
    property: G-TTH1YYW5TX
    provider: google
  consent:
    actions:
    - accept
    - reject
    - manage
    description: We use cookies to recognize your repeated visits and preferences,
      as well as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to make
      our documentation better.
    title: Cookie consent
  version:
    default: latest
    provider: mike
extra_css:
- stylesheets/extra.css
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- attr_list
- pymdownx.emoji:
    emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
    emoji_index: !!python/name:material.extensions.emoji.twemoji ''
- toc:
    permalink: '#'
nav:
- index.md
- Tutorials:
  - tutorials/installation.md
  - Create your first Tenant:
    - tutorials/tenant/create-tenant.md
    - tutorials/tenant/create-sandbox.md
    - tutorials/tenant/creating-namespaces.md
    - tutorials/tenant/assigning-metadata.md
    - tutorials/tenant/tenant-hibernation.md
    - tutorials/tenant/deleting-tenant.md
  - 'Template: Definition and Usage Guide':
    - tutorials/template/template.md
  - ArgoCD Multi-tenancy:
    - tutorials/argocd/enabling-multi-tenancy-argocd.md
  - Vault Multi-Tenancy:
    - tutorials/vault/enabling-multi-tenancy-vault.md
- How-to Guides:
  - how-to-guides/tenant.md
  - how-to-guides/integration-config.md
  - how-to-guides/quota.md
  - how-to-guides/template.md
  - how-to-guides/template-instance.md
  - how-to-guides/template-group-instance.md
  - Offboarding:
    - how-to-guides/offboarding/uninstalling.md
- Reference guides:
  - reference-guides/admin-clusterrole.md
  - reference-guides/configuring-multitenant-network-isolation.md
  - reference-guides/custom-roles.md
  - reference-guides/deploying-templates.md
  - reference-guides/distributing-resources.md
  - reference-guides/distributing-secrets.md
  - reference-guides/resource-sync-by-tgi.md
  - reference-guides/distributing-secrets-using-sealed-secret-template.md
  - reference-guides/extend-default-roles.md
  - reference-guides/integrationconfig.md
  - reference-guides/mattermost.md
  - reference-guides/secret-distribution.md
  - reference-guides/custom-metrics.md
  - reference-guides/keycloak.md
  - reference-guides/graph-visualization.md
- Explanation:
  - explanation/console.md
  - explanation/auth.md
  - explanation/why-argocd-multi-tenancy.md
- faq.md
- changelog.md
- eula.md
- troubleshooting.md
plugins:
- search
- mermaid2
- glightbox
repo_url: https://github.com/stakater/mto-docs
site_name: Multi Tenant Operator
site_url: https://docs.stakater.com/
theme:
  custom_dir: dist/_theme
  favicon: assets/images/favicon.svg
  features:
  - content.code.copy
  - navigation.tracking
  - toc.follow
  - toc.integrate
  - navigation.top
  font:
    code: Montserrat Mono
    text: Montserrat
  logo: assets/images/favicon.svg
  name: material
  palette:
  - media: (prefers-color-scheme)
    toggle:
      icon: material/brightness-auto
      name: Switch to system preference
  - accent: custom
    media: '(prefers-color-scheme: light)'
    primary: custom
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to light mode
  - accent: custom
    media: '(prefers-color-scheme: dark)'
    primary: custom
    scheme: slate
    toggle:
      icon: material/brightness-3
      name: Switch to dark mode
use_directory_urls: false
