name: Version deletion

on:
  delete

jobs:
  delete:
    uses: stakater/.github/.github/workflows/mkdocs_branch_deleted.yaml@v0.0.60
    secrets:
      GH_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
  