name: Pull Request

on:
  pull_request:
    branches:
      - "main"
      - "[0-9]+.[0-9]+"

jobs:
  doc_qa:
    uses: stakater/.github/.github/workflows/pull_request_doc_qa.yaml@v0.0.89
    with:
      MD_CONFIG: .github/md_config.json
      DOC_SRC: content
      MD_LINT_CONFIG: .markdownlint.yaml
  build_container:
    if: ${{ github.base_ref == 'main' }}
    uses: stakater/.github/.github/workflows/pull_request_container_build.yaml@v0.0.89
    with:
      DOCKER_BUILD_CONTEXTS: content=https://github.com/stakater/mto-docs.git#pull-request-deployments
      DOCKER_FILE_PATH: Dockerfile
    secrets:
      CONTAINER_REGISTRY_URL: ghcr.io/stakater
      CONTAINER_REGISTRY_USERNAME: stakater-user
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.STAKATER_GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
      DOCKER_SECRETS: GIT_AUTH_TOKEN=${{ secrets.STAKATER_GITHUB_TOKEN }}

  deploy_doc:
    uses: stakater/.github/.github/workflows/mkdocs_pull_request_versioned_doc.yaml@v0.0.89
    secrets:
      GH_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
